# Generated by Django 5.2.12 on 2026-03-24 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isbb',
            new_name='isbn',
        ),
    ]
